
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion-stock
    username: postgres
    password: hery
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 15
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
